python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets DETOX_DRUG --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/DETOX_DRUG --left-gram-context 3 --right-gram-context 2

# to execute for more target classes, replace "DETOX_DRUG" with new traget class
# sequencer.py will return an error and not execute if the --output [output dir] directory already exists

#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets FOOD_INSECURE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/FOOD_INSECURE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets HOUSE_INSTABLE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/HOUSE_INSTABLE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets JUSTICE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/JUSTICE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets MST --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/MST --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/SOCIAL_CONNECT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT_RS --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/SOCIAL_CONNECT_RS --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets JOB_INSTABLE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/JOB_INSTABLE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets ACCESS_MEANS --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/ACCESS_MEANS --left-gram-context 3 --right-gram-context 2
